FROM composer as composer
COPY . /app
RUN composer install --ignore-platform-reqs --no-scripts

FROM php:7.4-fpm-alpine

ARG PHPGROUP
ARG PHPUSER

ENV PHPGROUP=${PHPGROUP}
ENV PHPUSER=${PHPUSER}

RUN addgroup --system ${PHPGROUP}; exit 0
RUN adduser --system -G ${PHPGROUP} -s /bin/sh -D ${PHPUSER}; exit 0


WORKDIR '/app'



RUN sed -i "s/user = www-data/user = ${PHPUSER}/g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s/group = www-data/group = ${PHPGROUP}/g" /usr/local/etc/php-fpm.d/www.conf

RUN docker-php-ext-install pdo pdo_mysql


COPY . .
RUN chmod +x artisan
COPY --from=composer /app/vendor /app/vendor

EXPOSE 80
EXPOSE 8000
CMD ["php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "-R"]
CMD ["php", "artisan", "serve", "--host", "0.0.0.0"]

